language: node_js
node_js:
  - "8"
sudo: required
services:
  - docker
script:
  - sudo docker pull bitnami/redis:4.0.9 # For some reason I have to do this even though I tell docker to pull the image
  - yarn test
